Write-Host "Starting P.U.L.S.E..." -ForegroundColor Cyan

$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $projectRoot

# Pick the IPv4 address of the active interface that has a default gateway.
# This avoids hard-coding an old Wi-Fi/VPN address.
$lanIp = $null
$configs = Get-NetIPConfiguration -ErrorAction SilentlyContinue |
    Where-Object {
        $_.IPv4Address -and
        $_.IPv4DefaultGateway -and
        $_.IPv4Address.IPAddress -notlike "127.*" -and
        $_.IPv4Address.IPAddress -notlike "169.254.*"
    }

# Prefer normal private LAN addresses.
$lanIp = $configs |
    ForEach-Object { $_.IPv4Address.IPAddress } |
    Where-Object {
        $_ -match '^10\.' -or
        $_ -match '^192\.168\.' -or
        $_ -match '^172\.(1[6-9]|2[0-9]|3[0-1])\.'
    } |
    Select-Object -First 1

# Fallback to the first active IPv4 interface with a gateway.
if (-not $lanIp) {
    $lanIp = $configs |
        ForEach-Object { $_.IPv4Address.IPAddress } |
        Select-Object -First 1
}

if ($lanIp) {
    # This controls links generated by P.U.L.S.E (verification/activation emails).
    # The web server itself is already bound to 0.0.0.0 in application.properties.
    $env:PULSE_BASE_URL = "http://$lanIp`:8080"
}

# Optional local secret file. Copy .env.local.example -> .env.local and fill it in.
# .env.local is git-ignored. Values in the current PowerShell environment win.
$localEnvFile = Join-Path $projectRoot ".env.local"
if (Test-Path $localEnvFile) {
    Get-Content $localEnvFile | ForEach-Object {
        $line = $_.Trim()
        if ($line -and -not $line.StartsWith("#") -and $line -match '^([^=]+)=(.*)$') {
            $name = $matches[1].Trim()
            $value = $matches[2].Trim()
            # Accept normal .env quoting without exposing or logging secret values.
            if ($value.Length -ge 2) {
                $first = $value.Substring(0,1)
                $last = $value.Substring($value.Length - 1,1)
                if (($first -eq '"' -and $last -eq '"') -or ($first -eq "'" -and $last -eq "'")) {
                    $value = $value.Substring(1, $value.Length - 2)
                }
            }
            if (-not [Environment]::GetEnvironmentVariable($name, "Process")) {
                [Environment]::SetEnvironmentVariable($name, $value, "Process")
            }
        }
    }
}

# If the current shell already has Railway/Supabase variables, the child process
# inherits them. Do not put the database password in this script.
Start-Process powershell -ArgumentList "-NoExit", "-Command", "Set-Location '$projectRoot'; .\mvnw.cmd spring-boot:run '-Dspring-boot.run.profiles=dev,local'"

Write-Host ""
Write-Host "P.U.L.S.E is starting in a new terminal." -ForegroundColor Green
$cloudPassword = [Environment]::GetEnvironmentVariable("SPRING_DATASOURCE_PASSWORD", "Process")
if ($cloudPassword -and $cloudPassword -ne "REPLACE_ME") {
    Write-Host "Supabase password: loaded" -ForegroundColor Green
} else {
    Write-Host "Supabase password: NOT LOADED (check .env.local)" -ForegroundColor Red
}
Write-Host "Local: http://localhost:8080" -ForegroundColor Yellow

if ($lanIp) {
    Write-Host "LAN:   http://$lanIp`:8080" -ForegroundColor Cyan
    Write-Host "Email links: $env:PULSE_BASE_URL" -ForegroundColor Cyan
} else {
    Write-Host "LAN IP could not be detected automatically. Run 'ipconfig' to find it." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Make sure Windows Firewall allows TCP 8080 on the Private network." -ForegroundColor Yellow
