spring.application.name=pulse

# MySQL connection # FOR SANU NINEKKU CONFIGURE CHEYYAN
# the library that translates Java objects ↔ database rows - Hibernate (Just giving a heads up)
spring.datasource.url=jdbc:mysql://localhost:3306/pulse?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=BLZ4231
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080

spring.sql.init.mode=always