package com.pulse.local.service;

import com.pulse.local.model.LocalStockEntry;
import com.pulse.local.repository.LocalStockEntryRepository;
import com.pulse.model.Admin;
import com.pulse.model.DistrictAdmin;
import com.pulse.model.Hospital;
import com.pulse.model.Medicine;
import com.pulse.model.PharmacyStaff;
import com.pulse.model.StateAdmin;
import com.pulse.model.User;
import com.pulse.repository.HospitalRepository;
import com.pulse.repository.MedicineRepository;
import com.pulse.repository.UserRepository;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

import javax.sql.DataSource;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Hospital-local offline mirror. This is deliberately separate from the cloud JPA
 * model: the local node must remain usable when PostgreSQL/Supabase is unreachable.
 */
@Service
@Profile("local")
public class LocalOfflineStore {

    private final JdbcTemplate jdbc;
    private final HospitalRepository cloudHospitals;
    private final MedicineRepository cloudMedicines;
    private final UserRepository cloudUsers;
    private final LocalStockEntryRepository localStock;

    public LocalOfflineStore(@Qualifier("localDataSource") DataSource localDataSource,
                             HospitalRepository cloudHospitals,
                             MedicineRepository cloudMedicines,
                             UserRepository cloudUsers,
                             LocalStockEntryRepository localStock) {
        this.jdbc = new JdbcTemplate(localDataSource);
        this.cloudHospitals = cloudHospitals;
        this.cloudMedicines = cloudMedicines;
        this.cloudUsers = cloudUsers;
        this.localStock = localStock;
        initializeSchema();
    }

    private void initializeSchema() {
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS local_hospitals (
                hospital_id BIGINT PRIMARY KEY,
                name VARCHAR(150) NOT NULL,
                district VARCHAR(100),
                district_id BIGINT,
                government_hospital_key VARCHAR(64),
                latitude DOUBLE,
                longitude DOUBLE
            )
            """);
        jdbc.execute("ALTER TABLE local_hospitals ADD COLUMN IF NOT EXISTS government_hospital_key VARCHAR(64)");
        jdbc.execute("ALTER TABLE local_hospitals ADD COLUMN IF NOT EXISTS latitude DOUBLE");
        jdbc.execute("ALTER TABLE local_hospitals ADD COLUMN IF NOT EXISTS longitude DOUBLE");
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS local_medicines (
                medicine_id BIGINT PRIMARY KEY,
                name VARCHAR(150) NOT NULL,
                category VARCHAR(100),
                threshold INT NOT NULL,
                expiry_date DATE
            )
            """);
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS local_users (
                local_user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                cloud_user_id BIGINT,
                name VARCHAR(150) NOT NULL,
                username VARCHAR(80) NOT NULL UNIQUE,
                password VARCHAR(200) NOT NULL,
                role VARCHAR(30) NOT NULL,
                state_id BIGINT,
                district_id BIGINT,
                hospital_id BIGINT,
                enabled BOOLEAN NOT NULL DEFAULT TRUE,
                pending_sync BOOLEAN NOT NULL DEFAULT FALSE
            )
            """);
        jdbc.execute("CREATE INDEX IF NOT EXISTS idx_local_users_hospital ON local_users(hospital_id)");
    }

    public Optional<User> findLocalUserById(Long localUserId) {
        List<Map<String, Object>> rows = jdbc.queryForList("SELECT * FROM local_users WHERE local_user_id=?", localUserId);
        return rows.isEmpty() ? Optional.empty() : Optional.of(toUser(rows.get(0)));
    }

    public boolean isPendingLocalUser(Long localUserId) {
        Integer count = jdbc.queryForObject("SELECT COUNT(*) FROM local_users WHERE local_user_id=? AND pending_sync=TRUE", Integer.class, localUserId);
        return count != null && count > 0;
    }

    public Optional<User> findUser(String username) {
        List<Map<String, Object>> rows = jdbc.queryForList(
                "SELECT * FROM local_users WHERE LOWER(username)=LOWER(?)", username);
        if (rows.isEmpty()) return Optional.empty();
        Map<String, Object> r = rows.get(0);
        return Optional.of(toUser(r));
    }

    public Optional<Hospital> findHospital(Long hospitalId) {
        List<Map<String, Object>> rows = jdbc.queryForList(
                "SELECT * FROM local_hospitals WHERE hospital_id=?", hospitalId);
        if (rows.isEmpty()) return Optional.empty();
        Map<String, Object> r = rows.get(0);
        Hospital h = new Hospital(((Number) r.get("hospital_id")).longValue(),
                (String) r.get("name"), (String) r.get("district"));
        h.setDistrictId(number(r.get("district_id")));
        h.setGovernmentHospitalKey((String) r.get("government_hospital_key"));
        h.setLatitude(numberDouble(r.get("latitude")));
        h.setLongitude(numberDouble(r.get("longitude")));
        return Optional.of(h);
    }

    public List<User> staffForHospital(Long hospitalId) {
        return jdbc.queryForList("SELECT * FROM local_users WHERE hospital_id=? AND role='STAFF' ORDER BY name", hospitalId)
                .stream().map(this::toUser).toList();
    }

    public List<Hospital> hospitals() {
        return jdbc.query("SELECT * FROM local_hospitals ORDER BY name", (rs, i) -> {
            Hospital h = new Hospital(rs.getLong("hospital_id"), rs.getString("name"), rs.getString("district"));
            h.setDistrictId((Long) rs.getObject("district_id"));
            h.setGovernmentHospitalKey(rs.getString("government_hospital_key"));
            h.setLatitude((Double) rs.getObject("latitude"));
            h.setLongitude((Double) rs.getObject("longitude"));
            return h;
        });
    }

    public List<Medicine> medicines() {
        return jdbc.query("SELECT * FROM local_medicines ORDER BY name", (rs, i) -> {
            Medicine m = new Medicine(rs.getLong("medicine_id"), rs.getString("name"),
                    rs.getString("category"), rs.getInt("threshold"));
            java.sql.Date expiry = rs.getDate("expiry_date");
            if (expiry != null) m.setExpiryDate(expiry.toLocalDate());
            return m;
        });
    }

    public Optional<Medicine> findMedicine(Long medicineId) {
        return medicines().stream().filter(m -> medicineId.equals(m.getMedId())).findFirst();
    }

    public List<String> districts() {
        return jdbc.queryForList("SELECT DISTINCT district FROM local_hospitals WHERE district IS NOT NULL ORDER BY district", String.class);
    }

    public List<LocalStockEntry> stockForHospital(Long hospitalId) {
        return localStock.findByHospitalId(hospitalId);
    }

    /** Development-only seed so a fresh demo node can be started without Internet. */
    public void seedDemoReferenceData() {
        if (hasLocalData()) return;
        Object[][] hospitals = {
                {1L, "Kozhikode General Hospital", "Kozhikode", 2L, "7548818611", 11.25751, 75.77319},
                {2L, "Kozhikode District Hospital", "Kozhikode", 2L, null, null, null},
                {3L, "Ernakulam General Hospital", "Ernakulam", 1L, "3238837417", 9.9722768, 76.2813966}
        };
        for (Object[] h : hospitals) {
            jdbc.update("""
                MERGE INTO local_hospitals
                (hospital_id,name,district,district_id,government_hospital_key,latitude,longitude)
                KEY(hospital_id) VALUES (?,?,?,?,?,?,?)
                """, h);
        }
        Object[][] medicines = {
                {1L,"Paracetamol","Analgesic",50},{2L,"Insulin","Hormone",20},{3L,"Amoxicillin","Antibiotic",30},
                {4L,"Metformin","Antidiabetic",40},{5L,"Amlodipine","Antihypertensive",25},{6L,"Omeprazole","Antacid",30},
                {7L,"Cetirizine","Antihistamine",20},{8L,"Azithromycin","Antibiotic",15},{9L,"Salbutamol","Bronchodilator",10},{10L,"ORS Sachets","Rehydration",100}
        };
        for (Object[] m : medicines) {
            jdbc.update("MERGE INTO local_medicines (medicine_id,name,category,threshold,expiry_date) KEY(medicine_id) VALUES (?,?,?,?,?)",
                    m[0],m[1],m[2],m[3],null);
        }
        int[][] quantities = {
                {1,1,200},{1,2,5},{1,3,0},{1,4,80},{1,5,10},
                {2,6,60},{2,7,0},{2,8,5},{2,9,40},{2,10,150},
                {3,1,10},{3,2,30},{3,3,0},{3,4,15},{3,5,50}
        };
        for (int[] q : quantities) {
            if (localStock.findByHospitalIdAndMedicineId((long) q[0], (long) q[1]).isEmpty()) {
                LocalStockEntry e = new LocalStockEntry(); e.setHospitalId((long)q[0]); e.setMedicineId((long)q[1]); e.setQuantity(q[2]);
                e.setLastUpdated(LocalDate.now().toString()); e.setSynced(true); localStock.save(e);
            }
        }
    }

    public boolean hasLocalData() {
        Integer count = jdbc.queryForObject("SELECT COUNT(*) FROM local_hospitals", Integer.class);
        return count != null && count > 0;
    }

    /** Pull reference data from Supabase. A failure here is intentionally non-fatal. */
    public boolean refreshReferenceData() {
        try {
            for (Hospital h : cloudHospitals.findAll()) {
                jdbc.update("""
                    MERGE INTO local_hospitals
                    (hospital_id,name,district,district_id,government_hospital_key,latitude,longitude)
                    KEY(hospital_id) VALUES (?,?,?,?,?,?,?)
                    """, h.getHospitalId(), h.getName(), h.getDistrict(), h.getDistrictId(),
                    h.getGovernmentHospitalKey(), h.getLatitude(), h.getLongitude());
            }
            for (Medicine m : cloudMedicines.findAll()) {
                jdbc.update("""
                    MERGE INTO local_medicines (medicine_id,name,category,threshold,expiry_date)
                    KEY(medicine_id) VALUES (?,?,?,?,?)
                    """, m.getMedId(), m.getName(), m.getCat(), m.getThreshold(), m.getExpiryDate());
            }
            for (User u : cloudUsers.findAll()) {
                if (u.getUsername() == null) continue;
                jdbc.update("""
                    MERGE INTO local_users
                    (cloud_user_id,name,username,password,role,state_id,district_id,hospital_id,enabled,pending_sync)
                    KEY(username) VALUES (?,?,?,?,?,?,?,?,?,FALSE)
                    """, u.getUserId(), u.getName(), u.getUsername(), u.getPassword(), roleOf(u),
                        u.getStateId(), u.getDistrictId(), u.getHospitalId(), u.isEnabled());
            }
            return true;
        } catch (RuntimeException ex) {
            return false;
        }
    }

    public void mirrorUser(User user) {
        jdbc.update("""
            MERGE INTO local_users
            (cloud_user_id,name,username,password,role,state_id,district_id,hospital_id,enabled,pending_sync)
            KEY(username) VALUES (?,?,?,?,?,?,?,?,?,FALSE)
            """, user.getUserId(), user.getName(), user.getUsername(), user.getPassword(), roleOf(user),
                user.getStateId(), user.getDistrictId(), user.getHospitalId(), user.isEnabled());
    }

    public User createPendingUser(Long stateId, Long districtId, Long hospitalId,
                                  String name, String username, String encodedPassword,
                                  String role, boolean enabled) {
        jdbc.update("""
            INSERT INTO local_users
            (name,username,password,role,state_id,district_id,hospital_id,enabled,pending_sync)
            VALUES (?,?,?,?,?,?,?,?,TRUE)
            """, name, username, encodedPassword, role, stateId, districtId, hospitalId, enabled);
        return findUser(username).orElseThrow();
    }

    public int syncPendingUsers() {
        int synced = 0;
        List<Map<String, Object>> pending = jdbc.queryForList("SELECT * FROM local_users WHERE pending_sync=TRUE");
        for (Map<String, Object> row : pending) {
            try {
                String username = (String) row.get("username");
                User cloud = cloudUsers.findByUsername(username).orElse(null);
                if (cloud == null) {
                    cloud = switch ((String) row.get("role")) {
                        case "STATE_ADMIN" -> new StateAdmin();
                        case "DISTRICT_ADMIN" -> new DistrictAdmin();
                        case "ADMIN" -> new Admin();
                        default -> new PharmacyStaff();
                    };
                    cloud.setName((String) row.get("name"));
                    cloud.setUsername(username);
                    cloud.setPassword((String) row.get("password"));
                    cloud.setStateId(number(row.get("state_id")));
                    cloud.setDistrictId(number(row.get("district_id")));
                    cloud.setHospitalId(number(row.get("hospital_id")));
                    cloud.setEnabled(Boolean.TRUE.equals(row.get("enabled")));
                    cloud = cloudUsers.saveAndFlush(cloud);
                } else {
                    cloud.setName((String) row.get("name"));
                    cloud.setPassword((String) row.get("password"));
                    cloud.setStateId(number(row.get("state_id")));
                    cloud.setDistrictId(number(row.get("district_id")));
                    cloud.setHospitalId(number(row.get("hospital_id")));
                    cloud.setEnabled(Boolean.TRUE.equals(row.get("enabled")));
                    cloud = cloudUsers.saveAndFlush(cloud);
                }
                jdbc.update("UPDATE local_users SET cloud_user_id=?, pending_sync=FALSE WHERE local_user_id=?",
                        cloud.getUserId(), number(row.get("local_user_id")));
                synced++;
            } catch (RuntimeException ignored) {
                // Keep pending for the next retry.
            }
        }
        return synced;
    }

    public User createPendingStaff(Long stateId, Long districtId, Long hospitalId,
                                   String name, String username, String encodedPassword, boolean enabled) {
        jdbc.update("""
            INSERT INTO local_users
            (name,username,password,role,state_id,district_id,hospital_id,enabled,pending_sync)
            VALUES (?,?,?,?,?,?,?,?,TRUE)
            """, name, username, encodedPassword, "STAFF", stateId, districtId, hospitalId, enabled);
        return findUser(username).orElseThrow();
    }

    public void setStaffAuthorized(Long hospitalId, Long staffId, boolean authorized) {
        jdbc.update("UPDATE local_users SET enabled=?, pending_sync=TRUE WHERE local_user_id=? AND hospital_id=? AND role='STAFF'",
                authorized, staffId, hospitalId);
    }

    /** Push locally-created/modified accounts when cloud connectivity returns. */
    public int syncPendingStaff() { return syncPendingUsers(); }

    public User authenticateOffline(String username, String password, org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder encoder) {
        User user = findUser(username).orElseThrow(() -> new IllegalArgumentException("User not found"));
        if (!user.isEnabled()) throw new IllegalArgumentException("Account is not authorized");
        if (!encoder.matches(password, user.getPassword())) throw new IllegalArgumentException("Wrong password");
        return user;
    }

    private User toUser(Map<String, Object> r) {
        Long id = number(r.get("local_user_id"));
        String name = (String) r.get("name");
        String username = (String) r.get("username");
        String password = (String) r.get("password");
        String role = (String) r.get("role");
        User user = switch (role) {
            case "STATE_ADMIN" -> new StateAdmin(id, name, username, password);
            case "DISTRICT_ADMIN" -> new DistrictAdmin(id, name, username, password);
            case "ADMIN" -> new Admin(id, name, username, password);
            case "STAFF" -> new PharmacyStaff(id, name, username, password, number(r.get("hospital_id")));
            default -> new PharmacyStaff(id, name, username, password, number(r.get("hospital_id")));
        };
        user.setStateId(number(r.get("state_id")));
        user.setDistrictId(number(r.get("district_id")));
        user.setHospitalId(number(r.get("hospital_id")));
        user.setEnabled(Boolean.TRUE.equals(r.get("enabled")));
        return user;
    }

    private String roleOf(User user) {
        if (user instanceof StateAdmin) return "STATE_ADMIN";
        if (user instanceof DistrictAdmin) return "DISTRICT_ADMIN";
        if (user instanceof Admin) return "ADMIN";
        return "STAFF";
    }

    private static Long number(Object value) {
        return value == null ? null : ((Number) value).longValue();
    }

    private static Double numberDouble(Object value) {
        return value == null ? null : ((Number) value).doubleValue();
    }
}
